const ingredientsEN = {
  honey: "Honey",
  tableSugar: "Table Sugar",
  customIngredient: "Custom Ingredient",
  water: "Water",
  juice: "Juice",
  apples: "Apples",
  appleJuice: "Apple Juice",
  apricot: "Apricot",
  banana: "Banana",
  blackberry: "Blackberry",
  blueberry: "Blueberry",
  boysenberry: "Boysenberry",
  cantaloupe: "Cantaloupe",
  carrot: "Carrot",
  cherrySweet: "Cherry, Sweet",
  cherryTart: "Cherry, Tart",
  cranberry: "Cranberry",
  cranberryJuice: "Cranberry Juice",
  currantBlack: "Currant, Black",
  currantRed: "Currant, Red",
  datesDried: "Dates, Dried",
  elderberry: "Elderberry",
  figs: "Figs",
  figsDried: "Figs, Dried",
  gooseberry: "Gooseberry",
  grapefruit: "Grapefruit",
  grapefruitJuice: "Grapefruit Juice",
  grapesConcord: "Grapes, Concord",
  grapeJuicePurple: "Grape Juice, Purple",
  grapeJuiceWhite: "Grape Juice, White",
  guava: "Guava",
  honeydewMelon: "Honeydew Melon",
  jackfruit: "Jackfruit",
  kiwi: "Kiwi",
  lemonJuice: "Lemon Juice",
  limeJuice: "Lime Juice",
  lychee: "Lychee",
  mango: "Mango",
  mapleSyrup: "Maple Syrup",
  mulberry: "Mulberry",
  nectarine: "Nectarine",
  onion: "Onion",
  orangeJuice: "Orange Juice",
  papaya: "Papaya",
  passionFruit: "Passion  Fruit",
  peaches: "Peaches",
  pear: "Pear",
  persimmon: "Persimmon",
  pineapple: "Pineapple",
  plum: "Plum",
  pomegranate: "Pomegranate",
  pricklyPear: "Prickly Pear",
  prunes: "Prunes",
  raisins: "Raisins",
  raspberry: "Raspberry",
  rhubarb: "Rhubarb",
  strawberry: "Strawberry",
  tangerine: "Tangerine",
  tomato: "Tomato",
  tomatoJuice: "Tomato Juice",
  watermelon: "Watermelon",
};

export const ingredientTranslations = [ingredientsEN];
